### ISSUE TITLE
[BUG]: Can't add urls to a custom category

### ISSUE THREAD

**Issue by luchoArg33** [mitchos/pyZscaler#237]
Hello! Before writing the bug I just wanted to thank you for the library :) Have a nice day.

Describe the bug
----------------------
When I try to use the functions update_url_category or add_urls_to_category they don't work. I keep getting an error "Request body in invalid"

**To Reproduce**
This is my code:
cat_id = cat_list[x][1]
urls = [url]
result = zia.url_categories.add_urls_to_category(cat_id, urls=urls)
pprint(result.to_dict())

Expected behavior
------------------------
add the url to the category

Screenshots
----------------
[400: PUT] https://zsapi.zscalertwo.net/api/v1/urlCategories/CUSTOM_07?action=ADD_TO_LIST body=b'{"message":"Request body is invalid."}'
Traceback (most recent call last):
  File "c:\Users\luisa\test 1.py", line 50, in <module>
    result = zia.url_categories.add_urls_to_category(cat_id,urls=urls)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luisa\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyzscaler\zia\url_categories.py", line 279, in add_urls_to_category
    return self._put(f"urlCategories/{category_id}?action=ADD_TO_LIST", json=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luisa\AppData\Local\Programs\Python\Python312\Lib\site-packages\restfly\endpoint.py", line 225, in _put
    return self._req('PUT', path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luisa\AppData\Local\Programs\Python\Python312\Lib\site-packages\restfly\endpoint.py", line 81, in _req
    return self._api._req(method, new_path, **kwargs)  # noqa: PLW0212
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luisa\AppData\Local\Programs\Python\Python312\Lib\site-packages\restfly\session.py", line 559, in _req
    raise error_resp
restfly.errors.BadRequestError: [400: PUT] https://zsapi.zscalertwo.net/api/v1/urlCategories/CUSTOM_07?action=ADD_TO_LIST body=b'{"message":"Request body is invalid."}'

Additional context
-------------------------

**Comment by mitchos** [comment]
Hi @luchoArg33 I know it's been a long time since you posted this issue but did you ever end up resolving it?

I couldn't replicate the issue passing correct data types as arguments but I was able to replicate the issue passing an incorrect data type.

First I tested with a category ID as either a dict or list and in both cases I end up with a 500 error from Zscaler. Afterwards I tried passing a list inside a list `[[url]]` and I received a 400 - Request body is invalid. 

My best guess is that you need to check your data types for that code and ensure that urls is a list of strings.

**Comment by mitchos** [comment]
Can't replicate
